version: "3.9"
services:
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
  postgres:
    container_name: postgres
    image: postgres:15.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
  redis:
    container_name: redis
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
  nfs:
    container_name: nfs
    image: itsthenetwork/nfs-server-alpine
    ports:
      - "2049:2049"
    environment:
      SHARED_DIRECTORY: /var/nfsshare
