name: Docker Image CI

on:
  push:
    branches: [ "main", "git-actions" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Generate tag from timestamp
      id: image-tag
      run: |
        echo $(date +'%Y%m%d%H%M%S') >> tag.txt
        echo "tag=$(cat tag.txt)" >> $GITHUB_ENV


#    - uses: actions/checkout@v3
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag blueinit/auth-svc:${{ env.tag }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}     
    
#    - name: Push Docker image
#      run: docker push blueinit/auth-svc:${{ env.tag }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: blueinit/auth-svc:${{ env.tag }}


        
