name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'kubernetes/**' # Ignore changes to the "kubernetes" directory  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Generate tag from timestamp
      id: image-tag
      run: |
        echo $(date +'%Y%m%d%H%M%S') >> tag.txt
        echo "tag=$(cat tag.txt)" >> $GITHUB_ENV

    - name: Checkout code
      uses: actions/checkout@v2

#    - name: Install Docker and Docker Compose
#      run: |
#        sudo apt-get update
#        sudo apt-get -y install docker.io
#        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
#        sudo chmod +x /usr/local/bin/docker-compose

#    - name: Start services with Docker Compose
#      run: docker-compose up -d

    - uses: actions/checkout@v3
    - name: run docker-compose
      uses: sudo-bot/action-docker-compose@latest
      with:
        # https://docs.docker.com/compose/reference/overview/
        cli-args: "up -d"

    - name: Build and run Spring Boot application
      run: |
        ./gradlew build


    - name: Setup Gradle
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '19'
        cache: 'gradle'
    - uses: gradle/gradle-build-action@v2
    - run: ./gradlew build --no-daemon

    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag blueinit/auth-svc:${{ env.tag }} 
      
    - name: Login to Docker registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}     
    
    - name: Push Docker image
      run: docker push blueinit/auth-svc:${{ env.tag }}


    - uses: actions/checkout@v3
    - name: run docker-compose
      uses: sudo-bot/action-docker-compose@latest
      with:
        # https://docs.docker.com/compose/reference/overview/
        cli-args: "down"
        
